feat: Modified For Github Actions 6

diff --git a/.github/workflows/CICDDev.yml b/.github/workflows/CICDDev.yml
--- a/.github/workflows/CICDDev.yml
+++ b/.github/workflows/CICDDev.yml
@@ -25,18 +25,19 @@ jobs:
           docker-compose -f docker-compose-dev-CICD.yml up -d
       - name: Wait for App to be Ready
         run: |
-          for i in {1..30}; do
-            response=$(curl -s -o response.txt -w "%{http_code}" 127.0.0.1:8080/)
-            echo "HTTP Status: $response"
-            if [ "$response" -eq 200 ]; then
-              echo "App is up and running. Response:"
-              cat response.txt
-              break
-            else
-              echo "Waiting for app to be ready..."
-              sleep 10
+          counter=0
+          while ! curl -s localhost:8080/
+          do
+            counter=$((counter+1))
+            if [ $counter -gt 30 ]
+            then
+              echo "Failed to connect to app after 30 attempts."
+              exit 1
             fi
+            echo "Waiting for app to be ready..."
+            sleep 10
           done
+          echo "Connected to app successfully."
 
       - name: Run tests
         run: go test -v ./servertest
